name: wastash

description: "The Ultimate WhatsApp Status Saver App."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_onboarding: ^1.3.0
  cupertino_rounded_corners: ^2.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  heroine: ^0.4.0+1
  intl: ^0.20.2
  path_provider: ^2.1.5
  pull_down_button: ^0.10.2
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist/Geist-Bold.otf
          weight: 700
        - asset: assets/fonts/geist/Geist-SemiBold.otf
          weight: 600
    - family: GeistMono
      fonts:
        - asset: assets/fonts/geist/GeistMono-Regular.otf
          weight: 400

    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
