name: wastash

description: "The Ultimate WhatsApp Status Saver App."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_onboarding: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist/Geist-Bold.otf
          weight: 700
        - asset: assets/fonts/geist/Geist-SemiBold.otf
          weight: 600
    - family: GeistMono
      fonts:
        - asset: assets/fonts/geist/GeistMono-Regular.otf
          weight: 400

    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
